test:
  workers:
    number: 5
  rounds:
    - label: Create a document.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 2000
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/createDoc.js
    - label: Update document.
      txDuration: 20
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/updateDoc.js
        arguments:
          assets: 500
    - label: Read a document's version history.
      txDuration: 20
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/readDoc.js
        arguments:
          assets: 500
    - label: Delete a document.
      txDuration: 20
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/deleteDocs.js
        arguments:
          assets: 500